#!/bin/bash
rm *png desarrollo_graficos
make desarrollo_graficos
echo "Fin compilacion"
echo ""
echo "INICIANDO SIMULACION"
./desarrollo_graficos
echo "Fin simulacion"
#gedit datos_celulas datos_produccion 
